import datetime
t=datetime.time(22,56,44)     
print(t)
print("Hour:",t.hour)
print("Minute:",t.minute)
print("Second:",t.second)
print("microsecond:",t.microsecond)
print(".........,,,...........")

d=datetime.date.today()       
print(d)
print("Year:",d.year)
print("Month:",d.month)
print("Day:",d.day)
print("timeandcalmodule.py")

d1=datetime.date.today()
print(d1)
td=datetime.timedelta(days=2)     
print(td)
d2=d1+td                              
print(d2)
print("d2-d1=",d2-d1)                  
print("d2>d1=",d2>d1)                 
print(".........,,,,,..........")

d1=datetime.date.today()
t1=datetime.time(12,55,0)
dt=datetime.datetime.combine(d1,t1)   
print('dt:',dt)
